constant_db_model = "current_model"
constant_db_chat_mode = "current_chat_mode"
constant_db_api = "current_api"
constant_db_lang = "current_lang"
constant_db_tokens = "current_max_tokens"
continue_key = "Renounce€Countless€Unrivaled2€Banter"